name: CMake on a Single Platform

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure CMake
        run: |
          echo "Configuring CMake with build type: ${{ env.BUILD_TYPE }}"
          cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

      - name: Build
        run: |
          echo "Building the project..."
          cmake --build ${{ github.workspace }}/build --config ${{ env.BUILD_TYPE }} -- -j$(nproc)
          echo "Build completed successfully."

      - name: Test
        working-directory: ${{ github.workspace }}/build
        run: |
          echo "Running tests..."
          ctest -C ${{ env.BUILD_TYPE }} --output-on-failure
          echo "All tests executed."

      - name: Upload Build Artifacts
        if: success()  # Only run this step if previous steps succeeded
        uses: actions/upload-artifact@v3
        with:
          name: CMake Build Artifacts
          path: ${{ github.workspace }}/build
